WebWorstFitLRU/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebWorstFitLRU.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebWorstFitLRU/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WorstFitLRU;

namespace WebWorstFitLRU.Pages
{
    public class IndexModel : PageModel
    {
        public List<WorstFitModel> WorstFitModels { get; set; }
        public List<LRUModel> LRUModels { get; set; }
       
        public List<string> InputProcesses { get; set; }
        public List<string> InputBlocks { get; set; }
        public IActionResult OnGet()
        {
            WorstFitModels = new List<WorstFitModel>();
            LRUModels = new List<LRUModel>();
            return Page();
        }

        public IActionResult OnPostWorstFit(string blocksStr, string processesStr)
        {
            var blocksArr = blocksStr.Split(' ');
            var processesArr = processesStr.Split(' ');
            InputProcesses = processesArr.ToList();
            InputBlocks = blocksArr.ToList();
            var blocksList = new List<int>(blocksArr.Length);
            foreach (var i in blocksArr)
            {
                blocksList.Add(int.Parse(i));
            }
            var processesList = new List<int>(processesArr.Length);
            foreach (var i in processesArr)
            {
                processesList.Add(int.Parse(i));
            }
            WorstFitModels = Algos.WorstFit(blocksList.ToArray(), blocksList.Count, processesList.ToArray(), processesList.Count);
            LRUModels = new List<LRUModel>();
            return Page();
        }



    }
}

WebWorstFitLRU/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WorstFitLRU;

namespace WebWorstFitLRU.Pages
{
    public class PrivacyModel : PageModel
    {
        
        public List<LRUModel> LRUModels { get; set; }
        public int PageFaults { get; set; }
        public List<string> InputPages { get; set; }
        public int InputCapacity { get; set; }
      
        public IActionResult OnGet()
        {

            LRUModels = new List<LRUModel>();
            return Page();
        }

        public IActionResult OnPostLru(string pagesStr, int capacity)
        {
            var pagesArr = pagesStr.Split(' ');
            var pagesList = new List<int>(pagesArr.Length);
            foreach (var i in pagesArr)
            {
                pagesList.Add(int.Parse(i));
            }
            Algos.PageFaults(pagesList.ToArray(), capacity, out List<LRUModel> list);
            LRUModels = list;
            PageFaults = LRUModel.PageFaults;
            InputPages = pagesArr.ToList();
            InputCapacity = capacity;
            return Page();
        }
    }
}

WebWorstFitLRU/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1 class="display-4" style="text-align:center;">Worst Fit</h1>
<div class="container w-50">
    <form asp-page-handler="WorstFit" method="post">
        <div class="form-group">
            <label for="blocksStr">Enter blocks: </label>
            <input type="text" name="blocksStr" class="form-control" id="blocksStr">
        </div>
        <div class="form-group">
            <label for="processesStr">Enter processes: </label>
            <input type="text" name="processesStr" class="form-control" id="processesStr">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
@{
    if (Model.WorstFitModels.Count != 0)
    {
       

        <div class="container d-flex justify-content-center">
            <table class="table alert-succes bg-info w-50">
                <thead>
                    <tr>
                        <th scope="col">Process Number</th>
                        <th scope="col">Process size</th>
                        <th scope="col">Block number</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var i in Model.WorstFitModels)
                    {
                        <tr class="table-info">
                            <th scope="row">@i.ProcessNo</th>
                            <td>@i.ProcessSize</td>
                            <td>@i.BlockNo</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
}

WebWorstFitLRU/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebWorstFitLRU</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">WebWorstFitLRU</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebWorstFitLRU - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>